### ISSUE TITLE
Renders 3 line on first app render

### ISSUE THREAD

**Issue by susantpatel** [xiaody/react-lines-ellipsis#109]
I have passed max line 2 but it renders 3 lines when my react app first renders. Then when I resize my window it makes it 2 lines. The issue is on both firefox and chrome's latest versions.

**Comment by Pdhenrique** [comment]
I'm having the same problem.

As an example, I am working on a menuItem component that must have a title and smaller text below. This text would be limited by default to 2 lines. however, when this menuItem is applied to a component that uses it, it is being rendered with 3 lines, and then if it is re-rendered due to some update in the screen proportion, the 2 lines are applied.


![image](https://github.com/xiaody/react-lines-ellipsis/assets/129234362/0ff7ee3f-c817-4d19-a874-554664addc88)

Some properties, much of the stylization were removed from this image to reduce the size of the content.

In the images below I will show the way it is being rendered in my project.

initial render:
![image](https://github.com/xiaody/react-lines-ellipsis/assets/129234362/5bd39bf4-087f-4224-8de0-8ec89a0d5e70)

render after recalculation: 
![image](https://github.com/xiaody/react-lines-ellipsis/assets/129234362/e055e012-6298-4755-bf46-370fe9b35e9e)

**Comment by xiaody** [comment]
Close due to inactivity and no reproductions. Feel free to reopen with a stackblitz reproduction link.
